{% set name = "codetiming" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/codetiming-{{ version }}.tar.gz
  sha256: 2fcb4afb18e0ac8302e4e059d2d3343ee1df0ab84d26ddf8cd80b9205c9e67dc

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - flit-core
    - python >=3.6
  run:
    - python >=3.6
    - dataclasses

test:
  imports:
    - codetiming
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://realpython.com/python-timer
  dev_url: https://github.com/realpython/codetiming
  summary: A flexible, customizable timer for your Python code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
